from tkinter import *
root=Tk()
root.title("mainpage")
tFrame=Frame(root)
bFrame=Frame(root)
tFrame.pack()
bFrame.pack()
btn1=Button(tFrame,text="firstbutton",fg="green")
btn2=Button(tFrame,text="secondbutton",fg="red")
btn3=Button(tFrame,text="thirdbutton",fg="blue")
btn4=Button(bFrame,text="fourthbutton",fg="grey")
btn1.pack(side=LEFT)
btn2.pack(side=LEFT)
btn3.pack(side=LEFT)
btn4.pack(side=BOTTOM)
root.mainloop()
